/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication32;

import javax.swing.JSplitPane;

/**
 *
 * @author 117
 */
public class MainPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public MainPanel() {
        initComponents();
    }

    public PlotPanel getPlotPanel2() {
        return plotPanel2;
    }

    public JSplitPane getjSplitPane1() {
        return jSplitPane1;
    }

    public SettingPanel getSettingPanel1() {
        return settingPanel2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        settingPanel2 = new javaapplication32.SettingPanel();
        plotPanel2 = new javaapplication32.PlotPanel();

        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jSplitPane1.setDividerLocation(230);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setLeftComponent(settingPanel2);
        jSplitPane1.setRightComponent(plotPanel2);

        add(jSplitPane1);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane jSplitPane1;
    private javaapplication32.PlotPanel plotPanel2;
    private javaapplication32.SettingPanel settingPanel2;
    // End of variables declaration//GEN-END:variables
}
